export const FETCH_RECENT_POSTS = "FETCH_RECENT_POSTS";
export const FETCH_RECENT_POSTS_SUCCESS = "FETCH_RECENT_POSTS_SUCCESS";
export const FETCH_RECENT_POSTS_FAILURE = "FETCH_RECENT_POSTS_FAILURE";

export const FETCH_FOLLOWING_POSTS = "FETCH_FOLLOWING_POSTS";
export const FETCH_FOLLOWING_POSTS_SUCCESS = "FETCH_FOLLOWING_POSTS_SUCCESS";
export const FETCH_FOLLOWING_POSTS_FAILURE = "FETCH_FOLLOWING_POSTS_FAILURE";

export const FETCH_POPULAR_POSTS = "FETCH_POPULAR_POSTS";
export const FETCH_POPULAR_POSTS_SUCCESS = "FETCH_POPULAR_POSTS_SUCCESS";
export const FETCH_POPULAR_POSTS_FAILURE = "FETCH_POPULAR_POSTS_FAILURE";

export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";
